product_dic = {
               'p1' : ['Sony A7 R3',
                       'https://www.georges.com.au/sony-a7r-iii-mirrorless-digital-camera-body-only.html',
                       'https://www.digidirect.com.au/cameras/sony-alpha-a7r-iii-mirrorless-digital-camera-body-only',
                       'https://www.teds.com.au/sony-a7r-mark-3-body',
                       'https://www.camerapro.com.au/sony-alpha-a7r-mark-iii-mirrorless-camera.html'],
               'p2' : ['Sony A7 R4',
                       'https://www.georges.com.au/sony-a7r-mark-iv-body.html',
                       'https://www.digidirect.com.au/cameras/sony-a7r-mark-iv-body',
                       'https://www.teds.com.au/sony-a7r-mark-iv-body',
                       'https://www.camerapro.com.au/sony-a7r-mark-iv-mirrorless-camera-body-only.html'],
               'p3' : ['Sony A7 M3',
                       'https://www.georges.com.au/sony-a7-iii-mirrorless-digital-camera-body-only.html',
                       'https://www.digidirect.com.au/cameras/sony-alpha-a7-iii-mirrorless-digital-camera-body-only',
                       'https://www.teds.com.au/sony-a7-mark-3-body',
                       'https://www.camerapro.com.au/sony-a7-iii-mirrorless-camera-body-only.html'],
               'p4' : ['Sony A9 M1',
                       'https://www.georges.com.au/sony-a9-body.html',
                       'https://www.digidirect.com.au/cameras/sony-alpha-a9-mirrorless-digital-camera-body-only',
                       'https://www.teds.com.au/sony-a9-body',
                       'https://www.camerapro.com.au/sony-a9-mirrorless-camera.html'],
               'p5' : ['Sony A9 M2',
                       'https://www.georges.com.au/sony-alpha-a9-ii-mirrorless-digital-camera-body-only.html',
                       'https://www.digidirect.com.au/sony-alpha-a9-ii-body-only',
                       'https://www.teds.com.au/sony-a9-mark-2-body',
                       'https://www.camerapro.com.au/sony-alpha-a9-mark-ii-camera-body.html']
                }
